/*
 * Generated by JasperReports - 4/26/07 9:42 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import java.util.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class TravelDestinationReport_1177560752205_121928 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_PARAM_strTableNameNew = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_PARAM_strSiteIDnew = null;
    private JRFillParameter parameter_PARAM_strTravelTo = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_PARAM_strReportTitle = null;
    private JRFillParameter parameter_PARAM_strTableName = null;
    private JRFillParameter parameter_PARAM_strTravelType = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_PARAM_strTravelFrom = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillField field_TRAVEL_TO = null;
    private JRFillField field_REQUISTION_COUNT = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_Variable_Name = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_PARAM_strTableNameNew = (JRFillParameter)pm.get("PARAM_strTableNameNew");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_PARAM_strSiteIDnew = (JRFillParameter)pm.get("PARAM_strSiteIDnew");
        parameter_PARAM_strTravelTo = (JRFillParameter)pm.get("PARAM_strTravelTo");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_PARAM_strReportTitle = (JRFillParameter)pm.get("PARAM_strReportTitle");
        parameter_PARAM_strTableName = (JRFillParameter)pm.get("PARAM_strTableName");
        parameter_PARAM_strTravelType = (JRFillParameter)pm.get("PARAM_strTravelType");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_PARAM_strTravelFrom = (JRFillParameter)pm.get("PARAM_strTravelFrom");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_TRAVEL_TO = (JRFillField)fm.get("TRAVEL_TO");
        field_REQUISTION_COUNT = (JRFillField)fm.get("REQUISTION_COUNT");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_Variable_Name = (JRFillVariable)vm.get("Variable_Name");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("I");
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("01/10/2006");
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("12/10/2008");
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("T_JOURNEY_DETAILS_INT");
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("Destination Wise Report");
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)("T_TRAVEL_DETAIL_INT");
                break;
            }
            case 6 : 
            {
                value = (java.lang.String)("Destination Wise Report");
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " of ");
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + "");
                break;
            }
            case 17 : 
            {
                value = (java.lang.Comparable)(((java.lang.String)field_TRAVEL_TO.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Number)(((java.lang.Integer)field_REQUISTION_COUNT.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("I");
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("01/10/2006");
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("12/10/2008");
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("T_JOURNEY_DETAILS_INT");
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("Destination Wise Report");
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)("T_TRAVEL_DETAIL_INT");
                break;
            }
            case 6 : 
            {
                value = (java.lang.String)("Destination Wise Report");
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " of ");
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + "");
                break;
            }
            case 17 : 
            {
                value = (java.lang.Comparable)(((java.lang.String)field_TRAVEL_TO.getOldValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Number)(((java.lang.Integer)field_REQUISTION_COUNT.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("I");
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("01/10/2006");
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("12/10/2008");
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("T_JOURNEY_DETAILS_INT");
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("Destination Wise Report");
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)("T_TRAVEL_DETAIL_INT");
                break;
            }
            case 6 : 
            {
                value = (java.lang.String)("Destination Wise Report");
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 15 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " of ");
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + "");
                break;
            }
            case 17 : 
            {
                value = (java.lang.Comparable)(((java.lang.String)field_TRAVEL_TO.getValue()));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Number)(((java.lang.Integer)field_REQUISTION_COUNT.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
