
package webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsServer", targetNamespace = "http://ws.stars.mind/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsServer {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "printMessage", targetNamespace = "http://ws.stars.mind/", className = "webService.PrintMessage")
    @ResponseWrapper(localName = "printMessageResponse", targetNamespace = "http://ws.stars.mind/", className = "webService.PrintMessageResponse")
    public void printMessage();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getProducts", targetNamespace = "http://ws.stars.mind/", className = "webService.GetProducts")
    @ResponseWrapper(localName = "getProductsResponse", targetNamespace = "http://ws.stars.mind/", className = "webService.GetProductsResponse")
    public void getProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://ws.stars.mind/", className = "webService.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://ws.stars.mind/", className = "webService.GetProductCategoriesResponse")
    public void getProductCategories();

}
