
package webService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wsServerService", targetNamespace = "http://ws.stars.mind/", wsdlLocation = "http://localhost:8088/wsServer/server?wsdl")
public class WsServerService
    extends Service
{

    private final static URL WSSERVERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webService.WsServerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webService.WsServerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8088/wsServer/server?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8088/wsServer/server?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSSERVERSERVICE_WSDL_LOCATION = url;
    }

    public WsServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsServerService() {
        super(WSSERVERSERVICE_WSDL_LOCATION, new QName("http://ws.stars.mind/", "wsServerService"));
    }

    /**
     * 
     * @return
     *     returns WsServer
     */
    @WebEndpoint(name = "wsServerPort")
    public WsServer getWsServerPort() {
        return super.getPort(new QName("http://ws.stars.mind/", "wsServerPort"), WsServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsServer
     */
    @WebEndpoint(name = "wsServerPort")
    public WsServer getWsServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.stars.mind/", "wsServerPort"), WsServer.class, features);
    }

}
